import {app,BrowserWindow,Tray,Menu,nativeImage,ipcMain,Notification,screen,shell} from 'electron';
import Store from 'electron-store'; import path from 'node:path'; import {WebSocketServer,WebSocket} from 'ws';
const store=new Store({name:'allbee-focus'}); let main:BrowserWindow|null=null, companion:BrowserWindow|null=null, tray:Tray|null=null; let wss:WebSocketServer|null=null;
const defaultState:any={userName:'',companionName:'',companionId:'bee',level:1,xp:0,coins:0,happiness:75,energy:100,dailyGoal:60,focusMinutesToday:0,rules:[],tasks:[],missions:[],stats:{focusMinutes:0,sessions:0,tasksCompleted:0,currentStreak:0,longestStreak:0},settings:{patrol:true,enforcement:'complain',countdown:3,snooze:5,position:'bottom',wander:true,size:.9,speed:1,alwaysOnTop:true,speech:true,notifications:true,startup:false,theme:'dark'},streakDates:[],unlocked:['bee']};
function createMain(){main=new BrowserWindow({width:1280,height:820,minWidth:900,minHeight:620,backgroundColor:'#0b1220',webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false}});main.loadFile(path.join(__dirname,'../dist/index.html'));main.on('close',e=>{if(!app.isQuitting){e.preventDefault();main?.hide()}})}
function createCompanion(){const d=screen.getPrimaryDisplay();const b=state().settings;let x=d.workArea.x+d.workArea.width-160,y=d.workArea.y+d.workArea.height-150;if(b.position==='bottom')y=d.workArea.y+d.workArea.height-150;if(b.position==='top')y=d.workArea.y+30;if(b.position==='left')x=d.workArea.x+30;if(b.position==='right')x=d.workArea.x+d.workArea.width-160;companion=new BrowserWindow({width:150,height:150,x,y,frame:false,transparent:true,resizable:false,alwaysOnTop:b.alwaysOnTop,skipTaskbar:true,hasShadow:false,webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false}});companion.setIgnoreMouseEvents(false);companion.loadFile(path.join(__dirname,'../dist/index.html'),{query:{companion:'1'}});}
function state(){return {...defaultState,...(store.get('state') as any||{}),settings:{...defaultState.settings,...((store.get('state') as any||{}).settings||{})}}}
function notify(title:string,body:string){if(state().settings.notifications&&Notification.isSupported())new Notification({title,body}).show()}
function setupTray(){tray=new Tray(nativeImage.createFromDataURL('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAE0lEQVR42mNk+M/wHwAEYQBIWmQGAAJQAAcWq7bRAAAAAElFTkSuQmCC'));tray.setToolTip('AllBee Focus');tray.setContextMenu(Menu.buildFromTemplate([{label:'ALLBEE FOCUS',enabled:false},{label:'Show Companion',click:()=>companion?.show()},{label:'Start Focus',click:()=>main?.webContents.send('tray-focus')},{label:'Focus',click:()=>main?.show()},{label:'Change Companion',click:()=>main?.webContents.send('tray-companion')},{label:'Snooze Patrol',click:()=>main?.webContents.send('tray-snooze')},{label:'Missions',click:()=>main?.webContents.send('tray-missions')},{type:'separator'},{label:'Settings',click:()=>main?.show()},{label:'Quit AllBee Focus',click:()=>{app.isQuitting=true;app.quit()}}]));tray.on('double-click',()=>main?.show())}
function setupIPC(){ipcMain.handle('get-state',()=>state());ipcMain.handle('save-state',(_,s)=>{store.set('state',s);return true});ipcMain.on('notify',(_,x)=>notify(x.title,x.body));ipcMain.on('show-main',()=>main?.show());ipcMain.on('quit',()=>{app.isQuitting=true;app.quit()});ipcMain.on('open-extension-folder',()=>shell.openPath(path.join(process.resourcesPath,'extension')));}
function setupBrowserBridge(){wss=new WebSocketServer({port:18765,host:'127.0.0.1'});wss.on('connection',(ws:WebSocket)=>{ws.send(JSON.stringify({type:'hello',app:'AllBee Focus'}));ws.on('message',raw=>{try{const m=JSON.parse(raw.toString());if(m.type==='activeTab')main?.webContents.send('browser-tab',m)}catch{}})});}
app.whenReady().then(()=>{if(!store.has('state'))store.set('state',defaultState);setupIPC();setupTray();setupBrowserBridge();createMain();createCompanion();app.setLoginItemSettings({openAtLogin:state().settings.startup});app.on('activate',()=>main?.show())});
app.on('before-quit',()=>{app.isQuitting=true;wss?.close()});
