const {app,BrowserWindow,Tray,Menu,nativeImage,ipcMain,Notification,screen} = require('electron');
const path=require('path'),fs=require('fs');
let mainWin=null, companionWin=null, tray=null, quitting=false;
const dataFile=()=>path.join(app.getPath('userData'),'state.json');
const defaults={userName:'',companionId:'bee',companionName:'AllBee Bee',level:1,xp:0,coins:0,dailyGoal:60,focusToday:0,totalFocus:0,sessions:0,tasksCompleted:0,currentStreak:0,bestStreak:0,rules:[],tasks:[],settings:{patrol:true,enforcement:'complain',countdown:3,snooze:5,position:'bottom',wander:true,alwaysOnTop:true,speech:true,notifications:true,startup:false}};
function load(){try{return {...defaults,...JSON.parse(fs.readFileSync(dataFile(),'utf8'))}}catch{return {...defaults}}}
let state=load(); function save(){fs.mkdirSync(path.dirname(dataFile()),{recursive:true});fs.writeFileSync(dataFile(),JSON.stringify(state,null,2));}
function notify(title,body){if(state.settings.notifications&&Notification.isSupported())new Notification({title,body}).show()}
function createMain(){mainWin=new BrowserWindow({width:1180,height:760,minWidth:980,minHeight:620,backgroundColor:'#07131f',title:'AllBee Focus',webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false}});mainWin.loadFile(path.join(__dirname,'renderer','index.html'));mainWin.on('close',e=>{if(!quitting){e.preventDefault();mainWin.hide()}})}
function companionBounds(){const d=screen.getPrimaryDisplay(),w=d.workArea;let x=w.x+w.width-175,y=w.y+w.height-175;if(state.settings.position==='top')y=w.y+35;if(state.settings.position==='left')x=w.x+20;if(state.settings.position==='right')x=w.x+w.width-175;return{x,y}}
function createCompanion(){const b=companionBounds();companionWin=new BrowserWindow({width:160,height:160,x:b.x,y:b.y,frame:false,transparent:true,resizable:false,skipTaskbar:true,alwaysOnTop:state.settings.alwaysOnTop,hasShadow:false,webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false}});companionWin.setMenu(null);companionWin.loadFile(path.join(__dirname,'renderer','companion.html'));}
function traySetup(){const icon=nativeImage.createEmpty();tray=new Tray(icon);tray.setToolTip('AllBee Focus');tray.setContextMenu(Menu.buildFromTemplate([{label:'ALLBEE FOCUS',enabled:false},{type:'separator'},{label:'Show Dashboard',click:()=>mainWin.show()},{label:'Show Companion',click:()=>companionWin.show()},{label:'Start Focus',click:()=>mainWin.webContents.send('command','startFocus')},{label:'Change Companion',click:()=>mainWin.webContents.send('command','companion')},{label:'Snooze Patrol',click:()=>mainWin.webContents.send('command','snooze')},{type:'separator'},{label:'Quit AllBee Focus',click:()=>{quitting=true;app.quit()}}]));tray.on('double-click',()=>mainWin.show())}
ipcMain.handle('state',()=>state);ipcMain.handle('save',(_,next)=>{state={...state,...next};save();return state});ipcMain.on('notify',(_,x)=>notify(x.title,x.body));ipcMain.on('quit',()=>{quitting=true;app.quit()});ipcMain.on('companion-refresh',()=>{if(companionWin&&!companionWin.isDestroyed())companionWin.webContents.send('refresh',state)});
app.whenReady().then(()=>{save();traySetup();createMain();createCompanion();app.setLoginItemSettings({openAtLogin:!!state.settings.startup});app.on('activate',()=>mainWin.show())});app.on('before-quit',()=>{quitting=true;save()});
