import React,{useEffect,useMemo,useState} from 'react'; import {createRoot} from 'react-dom/client'; import {companions,iconFor} from './data'; import {Rule,State,Task} from './types'; import './styles.css';
const defaultState:State={userName:'',companionName:'',companionId:'bee',level:1,xp:0,coins:0,happiness:75,energy:100,dailyGoal:60,focusMinutesToday:0,rules:[],tasks:[],missions:[{id:'m1',title:'First Focus',description:'Complete 1 focus session',rewardXp:20,rewardCoins:20,progress:0,target:1,done:false},{id:'m2',title:'Deep Work',description:'Focus for 60 minutes',rewardXp:50,rewardCoins:50,progress:0,target:60,done:false},{id:'m3',title:'Task Master',description:'Complete 3 tasks',rewardXp:75,rewardCoins:75,progress:0,target:3,done:false}],stats:{focusMinutes:0,sessions:0,tasksCompleted:0,currentStreak:0,longestStreak:0},settings:{patrol:true,enforcement:'complain',countdown:3,snooze:5,position:'bottom',wander:true,size:.9,speed:1,alwaysOnTop:true,speech:true,notifications:true,startup:false,theme:'dark'},streakDates:[],unlocked:['bee'],};
const nav=[['home','⌂','Home'],['patrol','🐾','Patrol'],['focus','🎯','Focus'],['companion','🐾','My Companion'],['missions','🎯','Missions'],['stats','📊','Statistics'],['achievements','🏆','Achievements'],['collection','📚','Collection'],['shop','🛍','Shop'],['about','ℹ','About']];
function CompanionWindow(){const [state,setState]=useState<any>(null);useEffect(()=>{window.api?.getState().then(setState)},[]);if(!state)return null;const c=companions.find(x=>x.id===state.companionId)||companions[0];return <div className="mini"><div className="miniBubble">{state.settings?.speech?'Ready to focus?':''}</div><div className="miniAvatar">{iconFor(c.id)}</div><small>{state.companionName||c.name}</small></div>}
function App(){const [page,setPage]=useState('home'); const [state,setState]=useState<State>(defaultState); const [loaded,setLoaded]=useState(false); const [timer,setTimer]=useState(0); const [running,setRunning]=useState(false); const [taskText,setTaskText]=useState(''); const [notice,setNotice]=useState('');
useEffect(()=>{window.api?.getState().then((s:any)=>{if(s)setState(s);setLoaded(true)})},[]); useEffect(()=>{if(loaded)window.api?.saveState(state)},[state,loaded]);
useEffect(()=>{if(!running)return; const i=setInterval(()=>setTimer(t=>{if(t<=1){completeSession();return 0}return t-1}),1000);return()=>clearInterval(i)},[running]);
const comp=companions.find(c=>c.id===state.companionId)||companions[0]; const xpNeed=state.level*100; const xpPct=Math.min(100,state.xp/xpNeed*100);
function completeSession(){setRunning(false);setState(s=>{let xp=s.timerReward||25;let coins=10;let level=s.level, total=s.xp+xp;while(total>=level*100){total-=level*100;level++};const today=new Date().toISOString().slice(0,10);const dates=s.streakDates.includes(today)?s.streakDates:[...s.streakDates,today];const current=Math.max(s.stats.currentStreak,1);const missions=s.missions.map(m=>m.id==='m1'?{...m,progress:Math.min(m.target,m.progress+1),done:m.progress+1>=m.target}:m.id==='m2'?{...m,progress:Math.min(m.target,m.progress+(s.timerMinutes||25)),done:m.progress+(s.timerMinutes||25)>=m.target}:m);return {...s,xp:total,level,coins:s.coins+coins,focusMinutesToday:s.focusMinutesToday+(s.timerMinutes||25),stats:{...s.stats,focusMinutes:s.stats.focusMinutes+(s.timerMinutes||25),sessions:s.stats.sessions+1,currentStreak:current,longestStreak:Math.max(s.stats.longestStreak,current),lastFocusDate:today},streakDates:dates,missions}});setNotice('🎉 Focus session complete! +XP +10 Coins');setTimer(0)}
function startFocus(min=25,task?:Task){setState(s=>({...s,timerMinutes:min,timerReward:min===15?10:min===25?25:min===45?45:min===60?70:110} as any));setTimer(min*60);setRunning(true);if(task)setPage('focus')}
function addTask(){if(!taskText.trim())return;setState(s=>({...s,tasks:[...s.tasks,{id:crypto.randomUUID(),title:taskText,description:'',priority:'medium',estimate:25,completed:false}]}));setTaskText('')}
function toggleTask(id:string){setState(s=>{const tasks=s.tasks.map(t=>t.id===id?{...t,completed:!t.completed}:t);const done=tasks.filter(t=>t.completed).length;return {...s,tasks,stats:{...s.stats,tasksCompleted:done},missions:s.missions.map(m=>m.id==='m3'?{...m,progress:Math.min(m.target,done),done:done>=m.target}:m)}})}
function addRule(){const site=prompt('Website (example: instagram.com/reel)');if(!site)return;setState(s=>({...s,rules:[...s.rules,{id:crypto.randomUUID(),site:site.trim(),minutes:15,enabled:true,remaining:15,usedToday:0}]}))}
const Page=()=>{switch(page){case'patrol':return <Patrol/>;case'focus':return <Focus/>;case'companion':return <Companion/>;case'missions':return <Missions/>;case'stats':return <Stats/>;case'achievements':return <Achievements/>;case'collection':return <Collection/>;case'shop':return <Shop/>;case'about':return <About/>;default:return <Home/>}};
function Header({title,sub}:{title:string,sub:string}){return <><h1>{title}</h1><p className="sub">{sub}</p></>};
function Home(){return <><Header title={`Good ${new Date().getHours()<12?'morning':new Date().getHours()<18?'afternoon':'evening'} 👋`} sub="Ready to focus?"/><div className="hero card"><div><div className="eyebrow">CURRENT COMPANION</div><div className="compBig"><div className="avatar">{iconFor(comp.id)}</div><div><h2>{state.companionName||comp.name}</h2><span>Level {state.level} • {comp.power}</span><div className="bar"><i style={{width:`${xpPct}%`}}/></div></div></div></div><button className="primary" onClick={()=>startFocus(25)}>START FOCUS</button></div><div className="grid3"><Stat title="TODAY'S FOCUS" value={`${Math.floor(state.focusMinutesToday/60)}h ${state.focusMinutesToday%60}m / ${Math.floor(state.dailyGoal/60)}h`} /><Stat title="STREAK" value={`🔥 ${state.stats.currentStreak} days`}/><Stat title="ALLBEE COINS" value={`🪙 ${state.coins}`}/></div><div className="card"><div className="sectionHead"><h2>Next tasks</h2><span>{state.tasks.filter(t=>!t.completed).length} open</span></div><div className="addRow"><input value={taskText} onChange={e=>setTaskText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addTask()} placeholder="Add a task…"/><button onClick={addTask}>Add</button></div>{state.tasks.slice(0,5).map(t=><TaskRow key={t.id} t={t}/>)}</div>{notice&&<div className="toast" onClick={()=>setNotice('')}>{notice}</div>}</>}
function Stat(p:any){return <div className="card stat"><div className="eyebrow">{p.title}</div><strong>{p.value}</strong></div>}
function TaskRow({t}:{t:Task}){return <div className="task"><input type="checkbox" checked={t.completed} onChange={()=>toggleTask(t.id)}/><span className={t.completed?'done':''}>{t.title}</span><button onClick={()=>startFocus(t.estimate,t)}>Focus</button></div>}
function Patrol(){return <><Header title="Patrol" sub="When your companion gets up, what it watches, and what it does when it catches you."/><div className="card"><SettingToggle label="On patrol" desc="Turn the whole thing off without quitting." value={state.settings.patrol} on={()=>setState(s=>({...s,settings:{...s.settings,patrol:!s.settings.patrol}}))}/><h3>WHEN IT CATCHES YOU</h3><div className="choices"><label><input type="radio" checked={state.settings.enforcement==='complain'} onChange={()=>setState(s=>({...s,settings:{...s.settings,enforcement:'complain'}}))}/> Only complain <small>The companion reacts but never closes anything.</small></label><label><input type="radio" checked={state.settings.enforcement==='close'} onChange={()=>setState(s=>({...s,settings:{...s.settings,enforcement:'close'}}))}/> Close it <small>Requires the browser companion extension and explicit permission.</small></label></div><Field label="COUNTDOWN BEFORE IT ACTS"><input type="number" min="0" max="60" value={state.settings.countdown} onChange={e=>setState(s=>({...s,settings:{...s.settings,countdown:+e.target.value}}))}/><small>0–60 seconds</small></Field><Field label="SNOOZE LENGTH"><input type="number" min="1" max="60" value={state.settings.snooze} onChange={e=>setState(s=>({...s,settings:{...s.settings,snooze:+e.target.value}}))}/><small>1–60 minutes</small></Field><Field label="PATROL LOCATION"><select value={state.settings.position} onChange={e=>setState(s=>({...s,settings:{...s.settings,position:e.target.value as any}}))}><option>bottom</option><option>top</option><option>left</option><option>right</option><option>free</option></select></Field><SettingToggle label="Wander automatically" desc="Let the companion move around the desktop." value={state.settings.wander} on={()=>setState(s=>({...s,settings:{...s.settings,wander:!s.settings.wander}}))}/></div></>}
function Focus(){return <><Header title="Focus" sub="Set how much time you want to allow on distracting websites."/><div className="card"><div className="timer">{String(Math.floor(timer/60)).padStart(2,'0')}:{String(timer%60).padStart(2,'0')}</div><div className="presets">{[15,25,45,60,90].map(m=><button key={m} className="chip" onClick={()=>startFocus(m)}>{m} min</button>)}</div><div className="center"><button className="primary" onClick={()=>running?setRunning(false):startFocus(timer?Math.ceil(timer/60):25)}>{running?'PAUSE':'START FOCUS'}</button>{running&&<button onClick={()=>{setRunning(false);setTimer(0)}}>Finish Early</button>}</div></div><div className="card"><div className="sectionHead"><h2>Website rules</h2><button onClick={addRule}>+ Add a site</button></div>{state.rules.length===0?<Empty text="No distracting websites configured." button="Add a website" action={addRule}/>:state.rules.map(r=><div className="rule" key={r.id}><input type="checkbox" checked={r.enabled} onChange={()=>setState(s=>({...s,rules:s.rules.map(x=>x.id===r.id?{...x,enabled:!x.enabled}:x)}))}/><b>{r.site}</b><input type="number" min="1" value={r.minutes} onChange={e=>setState(s=>({...s,rules:s.rules.map(x=>x.id===r.id?{...x,minutes:+e.target.value,remaining:+e.target.value}:x)}))}/><span>{r.remaining} min left</span><button onClick={()=>setState(s=>({...s,rules:s.rules.filter(x=>x.id!==r.id)}))}>×</button></div>)}</div></>}
function Companion(){return <><Header title="My Companion" sub="Choose your productivity partner."/><div className="card profile"><div className="avatar huge">{iconFor(comp.id)}</div><h2>{state.companionName||comp.name}</h2><p>{comp.personality}</p><div className="bar"><i style={{width:`${xpPct}%`}}/></div><span>Level {state.level} • {state.xp}/{xpNeed} XP</span><div className="formGrid"><Field label="YOUR NAME"><input value={state.userName} onChange={e=>setState(s=>({...s,userName:e.target.value}))}/></Field><Field label="COMPANION NAME"><input value={state.companionName} onChange={e=>setState(s=>({...s,companionName:e.target.value}))}/></Field></div></div><div className="tabs"><button onClick={()=>setPage('collection')}>🐾 Pets</button><button onClick={()=>setPage('collection')}>🦸 Superheroes</button></div></>}
function Collection(){const [kind,setKind]=useState<'pet'|'hero'>('pet');return <><Header title="Collection" sub="Unlock original companions as you progress."/><div className="tabs"><button className={kind==='pet'?'active':''} onClick={()=>setKind('pet')}>🐾 Pets</button><button className={kind==='hero'?'active':''} onClick={()=>setKind('hero')}>🦸 Heroes</button></div><div className="cards">{companions.filter(c=>c.kind===kind).map(c=>{const locked=state.level<c.unlockLevel;return <div className={`char card ${locked?'locked':''}`} key={c.id}><div className="avatar">{iconFor(c.id)}</div><h3>{c.name}</h3><span>{c.rarity.toUpperCase()} • Level {c.unlockLevel}</span><p>{c.personality}</p>{locked?<button disabled>🔒 Unlock at Level {c.unlockLevel}</button>:<button onClick={()=>setState(s=>({...s,companionId:c.id}))}>{state.companionId===c.id?'SELECTED':'SELECT'}</button>}</div>})}</div></>}
function Missions(){return <><Header title="Missions" sub="Small challenges that keep your momentum moving."/><div className="cards">{state.missions.map(m=><div className="card mission" key={m.id}><div className="missionIcon">🎯</div><h2>{m.title}</h2><p>{m.description}</p><div className="bar"><i style={{width:`${Math.min(100,m.progress/m.target*100)}%`}}/></div><span>{m.progress}/{m.target}</span><div className="reward">+{m.rewardXp} XP • +{m.rewardCoins} Coins</div></div>)}</div></>}
function Stats(){return <><Header title="Statistics" sub="Your focus history at a glance."/><div className="grid3"><Stat title="FOCUS TIME" value={`${Math.floor(state.stats.focusMinutes/60)}h ${state.stats.focusMinutes%60}m`}/><Stat title="SESSIONS" value={state.stats.sessions}/><Stat title="TASKS COMPLETED" value={state.stats.tasksCompleted}/><Stat title="CURRENT STREAK" value={`${state.stats.currentStreak} days`}/><Stat title="BEST STREAK" value={`${state.stats.longestStreak} days`}/><Stat title="AVG SESSION" value={state.stats.sessions?`${Math.round(state.stats.focusMinutes/state.stats.sessions)} min`:'0 min'}/></div><div className="card chart"><h2>Focus progress</h2><div className="bars">{Array.from({length:7},(_,i)=><div key={i}><i style={{height:`${Math.max(8,Math.min(100,(state.focusMinutesToday/60)*25+(i*7)%30))}%`}}/><small>D{i+1}</small></div>)}</div></div></>}
function Achievements(){const a=[['🎯','First Focus',state.stats.sessions>=1],['🔥','Focus Beginner',state.stats.focusMinutes>=300],['🔥','Focus Master',state.stats.focusMinutes>=3000],['🔥','Focus Legend',state.stats.focusMinutes>=6000],['🔥','7 Day Streak',state.stats.currentStreak>=7],['🐾','Pet Collector',companions.filter(c=>c.kind==='pet'&&state.level>=c.unlockLevel).length>=5],['🦸','Hero Collector',companions.filter(c=>c.kind==='hero'&&state.level>=c.unlockLevel).length>=5],['🏆','Task Master',state.stats.tasksCompleted>=100],['🐝','AllBee Champion',state.stats.sessions>=100]];return <><Header title="Achievements" sub="Milestones earned through consistent focus."/><div className="cards">{a.map(x=><div className={`card achievement ${x[2]?'earned':''}`} key={x[1] as string}><div>{x[0]}</div><h3>{x[1]}</h3><span>{x[2]?'Unlocked':'Locked'}</span></div>)}</div></>}
function Shop(){return <><Header title="Shop" sub="Spend AllBee Coins on cosmetic rewards."/><div className="cards">{['Cozy Room','Study Room','Nature Room','Gaming Room','Space Room','Beach Room','Focus Desk','Companion Bed'].map((x,i)=><div className="card shop" key={x}><div className="shopArt">{['🏠','📚','🌿','🎮','🚀','🏖️','🪑','🛏️'][i]}</div><h3>{x}</h3><button onClick={()=>state.coins>=100&&setState(s=>({...s,coins:s.coins-100}))}>100 🪙</button></div>)}</div></>}
function About(){return <><Header title="About" sub="What you're running, and what AllBee Focus is built on."/><div className="card"><div className="eyebrow">VERSION</div><h2>v1.0.0</h2><p>AllBee Focus is a local-first productivity companion for Windows.</p><p className="muted">Focus. Grow. Achieve.</p></div><div className="card"><h2>Browser companion</h2><p>Install the included AllBee Focus browser extension to provide real URL/tab monitoring. Without it, the desktop app will explicitly report URL detection as unavailable rather than pretending it works.</p><button onClick={()=>window.api?.openExtensionFolder()}>Open Extension Folder</button></div><div className="card danger"><h2>Quit</h2><p>AllBee Focus lives in the Windows notification area. Closing this window does not quit the background application.</p><button onClick={()=>window.api?.quit()}>Quit AllBee Focus</button></div></>}
function Empty({text,button,action}:{text:string;button:string;action:()=>void}){return <div className="empty"><p>{text}</p><button onClick={action}>{button}</button></div>}
function Field({label,children}:{label:string;children:any}){return <label className="field"><b>{label}</b>{children}</label>}
function SettingToggle({label,desc,value,on}:{label:string;desc:string;value:boolean;on:()=>void}){return <div className="toggle"><div><b>{label}</b><small>{desc}</small></div><button className={value?'on':''} onClick={on}><i/></button></div>}
if(new URLSearchParams(window.location.search).get('companion')==='1') return <CompanionWindow/>;
return <div className="app"><aside><div className="brand">ALLBEE FOCUS<small>Focus. Grow. Achieve.</small></div>{nav.map(n=><button className={page===n[0]?'nav active':'nav'} onClick={()=>setPage(n[0])} key={n[0]}><span>{n[1]}</span>{n[2]}</button>)}<div className="saved">● Saved</div></aside><main><div className="top"><div className="live"><span className="dot"/> {running?'Focus session running':'Ready'}</div><div className="topcoins">🪙 {state.coins} • Lv {state.level}</div></div><Page/></main><div className="companion"><div className="bubble">{running?'Stay focused!':'Ready to focus?'}</div><div className="desktopAvatar">{iconFor(comp.id)}</div></div></div>}
declare global{interface Window{api:any}}
createRoot(document.getElementById('root')!).render(<App/>);
