const pets=[['bee','🐝','AllBee Bee','Friendly · Productive · Helpful',1,'mythic','pet'],['cat','🐱','Milo','Calm · Sleepy · Friendly',1,'common','pet'],['dog','🐶','Buddy','Energetic · Encouraging · Loyal',2,'common','pet'],['rabbit','🐰','Dash','Fast · Cheerful · Playful',3,'uncommon','pet'],['fox','🦊','Clever','Smart · Curious · Clever',5,'uncommon','pet'],['panda','🐼','Pogo','Relaxed · Calm',7,'rare','pet'],['owl','🦉','Sage','Study-focused · Wise',10,'rare','pet'],['lion','🦁','Roar','Confident · Motivational',15,'epic','pet'],['dragon','🐲','Draco','Rare · Powerful',20,'epic','pet'],['volt','⚡','Volt','Fast · Energetic · Motivating',4,'rare','hero'],['blaze','🔥','Blaze','Bold · Passionate',8,'epic','hero'],['aqua','🌊','Aqua','Calm · Focused',12,'epic','hero'],['aero','🌪️','Aero','Playful · Fast',16,'legendary','hero'],['terra','🌱','Terra','Disciplined · Patient',20,'legendary','hero'],['shadow','🌑','Shadow','Quiet · Mysterious',25,'legendary','hero'],['solara','☀️','Solara','Positive · Encouraging',30,'legendary','hero'],['frost','❄️','Frost','Calm · Precise',35,'mythic','hero'],['guardian','🛡️','Guardian','Reliable · Protective',40,'mythic','hero'],['nova','✨','Nova','Ambitious · Powerful',45,'mythic','hero'],['byte','💻','Byte','Smart · Coding-focused',50,'mythic','hero'],['orbit','🚀','Orbit','Curious · Adventurous',55,'mythic','hero'],['allbeehero','🐝','AllBee Hero','Friendly · Intelligent · Motivational',60,'mythic','hero']];
let S, page='home', timer=0, interval=null, selectedDuration=25, taskDraft='';
const nav=[['home','⌂','Home'],['patrol','◉','Patrol'],['focus','◷','Focus'],['companion','◈','My Companion'],['missions','◆','Missions'],['stats','▥','Statistics'],['achievements','★','Achievements'],['collection','▦','Collection'],['shop','◇','Shop'],['about','i','About']];
const A=window.allbee;
async function boot(){S=await A.getState();render();A.onCommand(c=>{if(c==='startFocus'){page='focus';startTimer(25)}if(c==='companion')page='companion';if(c==='snooze')toast('Patrol snoozed for '+S.settings.snooze+' minutes');render()})}
function companion(){return pets.find(x=>x[0]===S.companionId)||pets[0]}
function xpNeed(){return S.level*100}
function icon(){return companion()[1]}
function persist(){A.saveState(S);A.refreshCompanion()}
function setPage(p){page=p;render()}
function toast(t){const e=document.querySelector('.toast');if(e)e.remove();const n=document.createElement('div');n.className='toast';n.textContent=t;document.body.appendChild(n);setTimeout(()=>n.remove(),3000)}
function startTimer(m){selectedDuration=m;timer=m*60;if(interval)clearInterval(interval);interval=setInterval(()=>{timer--;renderTimer();if(timer<=0)completeSession()},1000);render()}
function renderTimer(){const e=document.querySelector('#timer');if(e){const m=Math.floor(timer/60),s=timer%60;e.textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}}
function pause(){if(interval){clearInterval(interval);interval=null;toast('Focus paused')}else if(timer>0){interval=setInterval(()=>{timer--;renderTimer();if(timer<=0)completeSession()},1000);toast('Focus resumed')}render()}
function completeSession(){if(interval)clearInterval(interval);interval=null;const mins=selectedDuration;S.focusToday+=mins;S.totalFocus+=mins;S.sessions++;S.currentStreak=Math.max(1,S.currentStreak);S.bestStreak=Math.max(S.bestStreak,S.currentStreak);S.coins+=10;let reward=mins===15?10:mins===25?25:mins===45?45:mins===60?70:110;S.xp+=reward;while(S.xp>=xpNeed()){S.xp-=xpNeed();S.level++;A.notify('AllBee Focus','Your companion reached Level '+S.level+'!')}S.happiness=Math.min(100,(S.happiness||75)+4);S.energy=Math.max(0,(S.energy||100)-3);timer=0;persist();A.notify('AllBee Focus','Focus session complete! +'+reward+' XP +10 Coins');toast('🎉 Focus complete · +'+reward+' XP · +10 Coins');render()}
function addTask(){const v=document.querySelector('#taskInput')?.value.trim();if(!v)return;S.tasks.push({id:Date.now(),title:v,completed:false,estimate:25});persist();render()}
function toggleTask(id){const t=S.tasks.find(x=>x.id===id);if(t){t.completed=!t.completed;S.tasksCompleted=S.tasks.filter(x=>x.completed).length;persist();render()}}
function addRule(){const site=prompt('Website (example: instagram.com/reel)');if(!site)return;const mins=parseInt(prompt('Time allowed in minutes','15'),10)||15;S.rules.push({id:Date.now(),site:site.trim(),minutes:mins,remaining:mins,enabled:true});persist();render()}
function selectComp(id){S.companionId=id;S.companionName=pets.find(x=>x[0]===id)[2];persist();toast(S.companionName+' selected');render()}
function render(){const root=document.querySelector('#app');root.innerHTML='<div class="app"><aside class="sidebar"><div class="brand">ALLBEE FOCUS</div><div class="tag">Focus. Grow. Achieve.</div>'+nav.map(n=>`<button class="nav ${page===n[0]?'active':''}" onclick="setPage('${n[0]}')"><span>${n[1]}</span>${n[2]}</button>`).join('')+'<div class="save">● Saved</div></aside><main class="main"><div class="top"><div class="live"><span class="dot"></span>${interval?'Focus session running':'Ready'}</div><div class="coins">🪙 ${S.coins} · Level ${S.level}</div></div>'+content()+'</main><div class="companion"><div class="bubble">${interval?'Stay focused!':'Ready to focus?'}</div><div class="avatar small">${icon()}</div></div></div>';if(page==='focus')renderTimer()}
function header(t,s){return `<h1 class="title">${t}</h1><div class="subtitle">${s}</div>`}
function content(){if(page==='home')return home();if(page==='patrol')return patrol();if(page==='focus')return focus();if(page==='companion')return compPage();if(page==='missions')return missions();if(page==='stats')return stats();if(page==='achievements')return achievements();if(page==='collection')return collection();if(page==='shop')return shop();return about()}
function home(){const c=companion();const pct=Math.round(S.xp/xpNeed()*100),day=Math.min(100,S.focusToday/S.dailyGoal*100);return header('Good '+(new Date().getHours()<12?'morning':new Date().getHours()<18?'afternoon':'evening')+' 👋','Ready to focus?')+`<div class="card hero"><div><div class="eyebrow">CURRENT COMPANION</div><div class="companionRow"><div class="avatar">${c[1]}</div><div><h2>${S.companionName||c[2]}</h2><div>Level ${S.level} · ${c[3]}</div><div class="bar"><i style="width:${pct}%"></i></div><small>${S.xp}/${xpNeed()} XP</small></div></div></div><button class="primary" onclick="setPage('focus');startTimer(25)">START FOCUS</button></div><div class="grid3" style="margin-top:16px"><div class="card stat"><div class="eyebrow">TODAY'S FOCUS</div><strong>${Math.floor(S.focusToday/60)}h ${S.focusToday%60}m / ${Math.floor(S.dailyGoal/60)}h</strong><div class="bar"><i style="width:${day}%"></i></div></div><div class="card stat"><div class="eyebrow">STREAK</div><strong>🔥 ${S.currentStreak} days</strong></div><div class="card stat"><div class="eyebrow">ALLBEE COINS</div><strong>🪙 ${S.coins}</strong></div></div><div class="card" style="margin-top:16px"><div class="sectionHead"><h2>Next tasks</h2><span>${S.tasks.filter(x=>!x.completed).length} open</span></div><div class="addRow"><input id="taskInput" placeholder="Add a task…" onkeydown="if(event.key==='Enter')addTask()"><button onclick="addTask()">Add</button></div>${S.tasks.slice(0,6).map(t=>taskRow(t)).join('')}</div>`}
function taskRow(t){return `<div class="task"><input type="checkbox" ${t.completed?'checked':''} onchange="toggleTask(${t.id})"><span class="${t.completed?'done':''}">${t.title}</span><button onclick="setPage('focus');startTimer(${t.estimate||25})">Focus</button></div>`}
function patrol(){return header('Patrol','When your companion gets up, what it watches, and what it does when it catches you.')+`<div class="card"><div class="toggle"><div><b>On patrol</b><small>Turn website enforcement off without quitting.</small></div><button class="switch ${S.settings.patrol?'on':''}" onclick="S.settings.patrol=!S.settings.patrol;persist();render()"><i></i></button></div><h3>WHEN IT CATCHES YOU</h3><div class="choices"><label><input type="radio" ${S.settings.enforcement==='complain'?'checked':''} onchange="S.settings.enforcement='complain';persist()"> Only complain<small>The companion reacts but never closes anything.</small></label><label><input type="radio" ${S.settings.enforcement==='close'?'checked':''} onchange="S.settings.enforcement='close';persist()"> Close it<small>Requires the browser extension and explicit permission.</small></label></div><div class="field"><b>COUNTDOWN BEFORE IT ACTS</b><input type="number" min="0" max="60" value="${S.settings.countdown}" onchange="S.settings.countdown=+this.value;persist()"><small>0–60 seconds</small></div><div class="field"><b>SNOOZE LENGTH</b><input type="number" min="1" max="60" value="${S.settings.snooze}" onchange="S.settings.snooze=+this.value;persist()"><small>1–60 minutes</small></div><div class="field"><b>PATROL LOCATION</b><select onchange="S.settings.position=this.value;persist()"><option value="bottom">Bottom of screen</option><option value="top">Top of screen</option><option value="left">Left edge</option><option value="right">Right edge</option><option value="free">Free movement</option></select></div><div class="toggle"><div><b>Wander automatically</b><small>Let the companion move around the desktop.</small></div><button class="switch ${S.settings.wander?'on':''}" onclick="S.settings.wander=!S.settings.wander;persist();render()"><i></i></button></div></div>`}
function focus(){return header('Focus','Run a dedicated distraction-free focus session.')+`<div class="card"><div id="timer" class="timer">00:00</div><div class="presets">${[15,25,45,60,90].map(m=>`<button class="chip" onclick="startTimer(${m})">${m} min</button>`).join('')}</div><div class="center"><button class="primary" onclick="${interval?'pause()':'startTimer('+selectedDuration+')'}">${interval?'PAUSE':'START FOCUS'}</button> <button class="secondary" onclick="if(interval)clearInterval(interval);interval=null;timer=0;render()">FINISH EARLY</button></div></div><div class="card" style="margin-top:16px"><div class="sectionHead"><h2>Website rules</h2><button class="secondary" onclick="addRule()">+ Add a site</button></div>${S.rules.length?S.rules.map((r,i)=>`<div class="rule"><input type="checkbox" ${r.enabled?'checked':''} onchange="S.rules[${i}].enabled=this.checked;persist()"><b style="flex:1">${r.site}</b><input type="number" value="${r.minutes}" onchange="S.rules[${i}].minutes=+this.value;S.rules[${i}].remaining=+this.value;persist()"><span>${r.remaining} min left</span><button onclick="S.rules.splice(${i},1);persist();render()">×</button></div>`).join(''):'<div class="empty">No distracting websites configured.<br><br><button class="secondary" onclick="addRule()">Add a website</button></div>'}</div>`}
function compPage(){return header('My Companion','Choose and customize your productivity partner.')+`<div class="card" style="text-align:center"><div class="avatar huge">${icon()}</div><h2>${S.companionName||companion()[2]}</h2><p>${companion()[3]}</p><div class="bar" style="margin:12px auto"><i style="width:${Math.round(S.xp/xpNeed()*100)}%"></i></div><p>Level ${S.level} · ${S.xp}/${xpNeed()} XP</p><div class="grid2"><div class="field"><b>YOUR NAME</b><input value="${S.userName}" onchange="S.userName=this.value;persist()"></div><div class="field"><b>COMPANION NAME</b><input value="${S.companionName}" onchange="S.companionName=this.value;persist()"></div></div></div>`}
function missions(){const ms=[['First Focus','Complete 1 focus session',S.sessions,1,20,20],['Deep Work','Focus for 60 minutes',S.focusToday,60,50,50],['Task Master','Complete 3 tasks',S.tasksCompleted,3,75,75]];return header('Missions','Small challenges that keep your momentum moving.')+`<div class="cards">${ms.map(m=>`<div class="card mission"><div class="missionIcon">🎯</div><h2>${m[0]}</h2><p>${m[1]}</p><div class="bar"><i style="width:${Math.min(100,m[2]/m[3]*100)}%"></i></div><p>${Math.min(m[2],m[3])}/${m[3]}</p><div class="reward">+${m[4]} XP · +${m[5]} Coins</div></div>`).join('')}</div>`}
function stats(){return header('Statistics','Your focus history at a glance.')+`<div class="grid3"><div class="card stat"><div class="eyebrow">FOCUS TIME</div><strong>${Math.floor(S.totalFocus/60)}h ${S.totalFocus%60}m</strong></div><div class="card stat"><div class="eyebrow">SESSIONS</div><strong>${S.sessions}</strong></div><div class="card stat"><div class="eyebrow">TASKS COMPLETED</div><strong>${S.tasksCompleted}</strong></div><div class="card stat"><div class="eyebrow">CURRENT STREAK</div><strong>${S.currentStreak} days</strong></div><div class="card stat"><div class="eyebrow">BEST STREAK</div><strong>${S.bestStreak} days</strong></div><div class="card stat"><div class="eyebrow">AVG SESSION</div><strong>${S.sessions?Math.round(S.totalFocus/S.sessions):0} min</strong></div></div>`}
function achievements(){const a=[['🎯','First Focus',S.sessions>=1],['🔥','Focus Beginner',S.totalFocus>=300],['🔥','Focus Master',S.totalFocus>=3000],['🔥','Focus Legend',S.totalFocus>=6000],['🔥','7 Day Streak',S.currentStreak>=7],['🐾','Pet Collector',S.level>=7],['🦸','Hero Collector',S.level>=20],['🏆','Task Master',S.tasksCompleted>=100],['🐝','AllBee Champion',S.sessions>=100]];return header('Achievements','Milestones earned through consistent focus.')+`<div class="cards">${a.map(x=>`<div class="card achievement ${x[2]?'earned':''}"><div>${x[0]}</div><h3>${x[1]}</h3><span>${x[2]?'Unlocked':'Locked'}</span></div>`).join('')}</div>`}
function collection(){return header('Collection','Original pets and original superheroes.')+`<div class="tabs"><button class="active" onclick="this.parentElement.nextElementSibling.innerHTML=collectionCards('pet')">🐾 Pets</button><button onclick="this.parentElement.nextElementSibling.innerHTML=collectionCards('hero')">🦸 Heroes</button></div><div id="collectionCards" class="cards">${collectionCards('pet')}</div>`}
function collectionCards(kind){return pets.filter(x=>x[6]===kind).map(c=>{const locked=S.level<c[4];return `<div class="card char ${locked?'locked':''}"><div class="avatar">${c[1]}</div><h3>${c[2]}</h3><span>${c[5].toUpperCase()} · Unlock Lv ${c[4]}</span><p>${c[3]}</p><button ${locked?'disabled':''} onclick="selectComp('${c[0]}')">${locked?'🔒 LOCKED':S.companionId===c[0]?'SELECTED':'SELECT'}</button></div>`}).join('')}
function shop(){return header('Shop','Use AllBee Coins for cosmetic rewards.')+`<div class="cards">${['Cozy Room','Study Room','Nature Room','Gaming Room','Space Room','Beach Room'].map((x,i)=>`<div class="card shop"><div style="font-size:45px">${['🏠','📚','🌿','🎮','🚀','🏖️'][i]}</div><h3>${x}</h3><p>Cosmetic theme</p><button class="secondary" onclick="if(S.coins>=100){S.coins-=100;persist();toast('Purchased '+x)}else toast('You need 100 AllBee Coins')">100 🪙</button></div>`).join('')}</div>`}
function about(){return header('About','What you’re running, and what AllBee Focus is built on.')+`<div class="card"><div class="eyebrow">VERSION</div><h2>v1.0.0</h2><p>AllBee Focus is a local-first Windows productivity companion.</p><p style="color:var(--muted)">Focus. Grow. Achieve.</p></div><div class="card" style="margin-top:16px"><h2>Browser monitoring</h2><p style="color:var(--muted)">Install the included browser extension for real active-tab URL detection. The app never pretends monitoring is active when the bridge is unavailable.</p></div><div class="card" style="margin-top:16px"><h2>Quit</h2><p style="color:var(--muted)">Closing this dashboard hides it; AllBee Focus remains in the Windows notification area.</p><button class="secondary" onclick="A.quit()">Quit AllBee Focus</button></div>`}
window.setPage=setPage;window.startTimer=startTimer;window.pause=pause;window.completeSession=completeSession;window.addTask=addTask;window.toggleTask=toggleTask;window.addRule=addRule;window.selectComp=selectComp;boot();
